### ISSUE TITLE
Incorrect comparision operator in Persistense.php

### ISSUE THREAD

**Issue by ghost** [pusher-community/realtime-commenting#1]
I think in function validate_input '===' should be used instead of '=='

Consider the following example
[1] > $str = '';
// ''
[2] > $str == false ? true : false;
// true
[3] > $str === false ? true : false;
// false

Which means check_string will work incorrectly for empty strings when $min_size = 0 specified.

**Comment by leggetter** [comment]
@EvgenyKovalev - you are right. The `Persistence.php` file really was just there to allow me to avoid using a database as part of the article. I wouldn't expect anybody to really use it. I'd be more than happy to accept a pull request if you'd like to contribute?

**Comment by ghost** [comment]
@leggetter I randomly surfed from your web site to github and randomly selected one of the projects/file to look into :) This spot just grabbed my attention. If this is not a production but illustrating code there is not much sense to make it top-notch :) Let's leave it as it is :+1:

**Comment by leggetter** [comment]
Cool. Definitely worth a comment to check :+1:
